# Generated by Django 5.1.4 on 2024-12-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0001_initial'),
        ('grow', '0002_remove_cultivation_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='cultivation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grow.cultivation'),
        ),
    ]
