# Generated by Django 5.1.4 on 2024-12-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0004_remove_humiditycontroltype_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='humiditycontrol',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='humiditycontrol',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='humiditycontrol',
            name='user',
        ),
        migrations.RemoveField(
            model_name='light',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='light',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='light',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temperaturecontrol',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='temperaturecontrol',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='temperaturecontrol',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ventilation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ventilation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ventilation',
            name='user',
        ),
    ]
