# Generated by Django 5.1.4 on 2024-12-23 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('growth_stage', models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('harvest', 'Harvest')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='envs.environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
