# Generated by Django 5.1.4 on 2024-12-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivation',
            name='environment',
        ),
    ]
